engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
exclude_paths:
- "spec/"
- "app/channels/**/*"
- "app/controllers/users_controller.rb"
- "app/controllers/tests_controller.rb"
- "app/models/user.rb"
- "app/controllers/application_controller.rb"
- "app/mailers/**/*"
- "app/jobs/**/*"
