engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
ratings:
   paths:
   - app/**
   - lib/**
   - "**.rb"
exclude_paths:
- "spec/**/*"
