language: ruby
rvm:
- 2.4.0
deploy:
  provider: heroku
  api_key:
    secure: lqFrMVFbEbhjM9LxrbnpMTzr6pjopVevvR6gOtyASt9pfZAd5SSNWk86f9vg0WflZf6sgpF5ob+/L4+/LcxJONYOvsMIOhkQd4pruQ7X/dQrugKY7yf54urDT4AdL0nyMxmSXn8Lc06d8k1h6OO48TVYDBk34xu9+Kl5oJ4UH3TgbyQQuDxfBc7HWkOXetpcxji7hg64fyWdZ01iV/dacY8/c9RmkjJ5N3Pkva9D/n22vY6whakFXnKotPujtWppCa7o6wNQmkbjTgJUqvdKoK0P4memfmXJgsFnmgup2ET1I2mgrxY/2BjVJob6Sv7kc6n+FkygiZVsAKGaKxKt32Rq2b0dpfjgalmblE0gHAsenW7Zrg2KPwuee3rM/WOw9QpEQwobDTZbred15JZp5B4TksfvWu1eGayYP012EaNyLZBaRVUYR9p6R3vRmhyP44PXDiEoqIftMfiXK10Gs2tLNojmjWICysjgN62er31iStGIMSmxrE9g/nVQJPVb45mKP4UpsuRqAFLg833yutGt7TJBlXZ9tVMU3e8KuvsX2eqrhzC67uIPWhmyfyILmQbbjo+A0rlIt6Sl0FOqe7J/fNnAx73UFBWjiDl5htaNWQMPkQWcViqHya6/gbqAxvhTXNwRS1eAw0MzMa4W12SoteKRvodzStkuXSPJnsM=
  app: pure-inlet-98383
  on:
    repo: OhtuKisalli/kisallioppiminen.server
