version: "2"
services:
  db:
    image: postgres:9.6
    ports:
      - "5432"
    environment:
      PGDATA: /data/postgres_db
    volumes:
      - db-data:/data/postgres_db
  web:
    depends_on:
      - db

volumes:
  db-data:
