#docker-compose.override.yml
version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -e development -p 3000 -b '0.0.0.0'
    #sync sourcecode to container (only in development!)
    volumes:
      - .:/kisalliserver
    ports:
      - "5555:3000"